server:
    bind:
        host: 0.0.0.0
        port: 3000
    url: http:/sbg-plants-load-balancer-1339052520.us-west-2.elb.amazonaws.com:3000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
        - fr-CA
    # cors: true
    pretty_print: true
    limit: 10
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
#    manager:
#        name: TinyDB
#        connection: /tmp/pygeoapi-process-manager.db
#        output_dir: /tmp/
    # ogc_schemas_location: /opt/schemas.opengis.net
    
logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: pygeoapi default instance
            fr: instance par défaut de pygeoapi
        description:
            en: pygeoapi provides an API to geospatial data
            fr: pygeoapi fournit une API aux données géospatiales
        keywords:
            en:
                - geospatial
                - data
                - api
            fr:
                - géospatiale
                - données
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: https://example.org
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

resources:
    test:
        type: collection
        title: test 
        description: test demo data
        keywords:
            - test
            - test
        extents:
            spatial:
                bbox: [-180, -90, 180, 90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: null
                end: null  # or empty (either means open ended)
        providers:
          - type: feature
            name: PostgreSQL
            data:
                host: terraform-20240726193642873600000001.cnjkti6fbqmw.us-west-2.rds.amazonaws.com
                dbname: sbgplants
                user: postgrest_user
                password: q7U1VWDqV9N5LX76TaXSnfyndsMTRApz
                search_path: [sbg_plants]
            options:
                # Maximum time to wait while connecting, in seconds.
                connect_timeout: 10
                # Number of *milliseconds* that transmitted data may remain
                # unacknowledged before a connection is forcibly closed.
                tcp_user_timeout: 10000
                # Whether client-side TCP keepalives are used. 1 = use keepalives,
                # 0 = don't use keepalives.
                keepalives: 1
                # Number of seconds of inactivity after which TCP should send a
                # keepalive message to the server.
                keepalives_idle: 5
                # Number of TCP keepalives that can be lost before the client's
                # connection to the server is considered dead.
                keepalives_count: 5
                # Number of seconds after which a TCP keepalive message that is not
                # acknowledged by the server should be retransmitted.
                keepalives_interval: 1
            id_field: id
            table: areas
            geom_field: geom
            crs:
              - http://www.opengis.net/def/crs/EPSG/0/4326
            storage_crs: http://www.opengis.net/def/crs/EPSG/0/4326

    lakes:
        type: collection
        title:
            en: Large Lakes
            fr: Grands Lacs
        description:
            en: lakes of the world, public domain
            fr: lacs du monde, domaine public
        keywords:
            en:
                - lakes
                - water bodies
            fr:
                - lacs
                - plans d'eau
        links:
            - type: text/html
              rel: canonical
              title: information
              href: http://www.naturalearthdata.com/
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
            temporal:
                begin: 2011-11-11T11:11:11Z
                end: null  # or empty (either means open ended)
        providers:
            - type: feature
              name: GeoJSON
              data: tests/data/ne_110m_lakes.geojson
              id_field: id
              title_field: name

    mapserver_world_map:
        type: collection
        title: MapServer demo WMS world map
        description: MapServer demo WMS world map
        keywords:
            - MapServer
            - world map
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://demo.mapserver.org
              hreflang: en-US
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        providers:
            - type: map
              name: WMSFacade
              data: https://demo.mapserver.org/cgi-bin/msautotest
              options:
                  layer: world_latlong
                  style: default
              format:
                    name: png
                    mimetype: image/png

    gdps-temperature:
        type: collection
        title: Global Deterministic Prediction System sample
        description: Global Deterministic Prediction System sample
        keywords:
            - gdps
            - global
        extents:
            spatial:
                bbox: [-180,-90,180,90]
                crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        links:
            - type: text/html
              rel: canonical
              title: information
              href: https://eccc-msc.github.io/open-data/msc-data/nwp_gdps/readme_gdps_en
              hreflang: en-CA
        providers:
            - type: coverage
              name: rasterio
              data: tests/data/CMC_glb_TMP_TGL_2_latlon.15x.15_2020081000_P000.grib2
              options:
                  DATA_ENCODING: COMPLEX_PACKING
              format:
                  name: GRIB
                  mimetype: application/x-grib2

  